apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: dev
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
