apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    manifests:
      - deployment.yaml
      - service.yaml
  pipeline:
    stages:
      - name: WAIT_APPROVAL
      - name: K8S_PRIMARY_ROLLOUT
